# SITE SETTINGS
title: extremedesigners
author:
  name: "Kevin Driedger"
  emails: 
   - "linuxbox+extremedesigners_ca@gmail.com"
   -  "linuxbox@extremedesigners.ca"
description: "Very quick version controlled static website"
baseurl: "" # Set if deploying to a subpath
url: "http://www.extremedesigners.ca"

# PLUGINS
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# BUILD
destination: ./_site

# MARKDOWN AND SYNTAX
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge

# EXCLUDES
exclude:
  - "README.md"
  - ".gitignore"
