# SITE SETTINGS
title: extremedesigners
author:
  name: "Kevin Driedger"
  emails: 
   - "linuxbox+extremedesigners_ca@gmail.com"
   -  "linuxbox@extremedesigners.ca"
description: "Very quick version controlled static website"
baseurl: "" # Set if deploying to a subpath
url: "http://www.extremedesigners.ca"

# PLUGINS
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# BUILD
destination: ./_site

# MARKDOWN AND SYNTAX
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge

# EXCLUDES
exclude:
  - "README.md"
  - ".gitignore"

# INCLUDES
include:
  - web # (for flutter2048)

# CUSTOM VARIABLES

# Font for header
headerfont_url: "https://fonts.googleapis.com/css2?family=Bitcount+Grid+Single:wght@400&display=swap"
headerfont_family: "'Bitcount Grid Single', sans-serif"

# Font for text
textfont_url: "https://fonts.googleapis.com/css2?family=Anonymous+Pro&display=swap"
textfont_family: "'Anonymous Pro', sans-serif"

# Typing header text effect
hover_title: home?
mistake_title: extremeprogramming
title_fix_delay: 1000
type_speed: # (speed in ms)
  slow: 100 
  fast: 50 
delete_speed: # (speed in ms)
  slow: 70
  fast: 40
intro_delete_delay: 250 # (speed in ms)
delete_delay: 110
cursor_flash_delay: 1500

